---

- name: Copy backend to temp
  become: true
  copy:
    src: /root/project/backend.tar.gz
    dest: /tmp

- name: Unzip backend
  become: true
  unarchive:
    src: /tmp/backend.tar.gz
    dest: /home/ubuntu
    remote_src: yes

- name: cd backend
  shell: |
    cd backend
    
# - name: npm install -g npm@latest
#   become: true
#   shell: |
#     npm install -g npm@latest
    
# - name: Start Server
#   become: true
#   shell: |
#     cd backend
#     npm install
#     npm audit fix -f
#     npm audit fix
#     npm run build
#     npm start:prod
    
- name: npm install
  become: true
  shell: |
    cd backend
    npm install

- name: npm install PM2
  become: true
  shell: |
    cd backend
    npm install pm2@latest -g

- name: Start Server
  become: true
  shell: |
    cd backend
    pm2 --name backend start npm -- start