---

- name: Copy backend to temp
  become: true
  copy:
    src: /root/project/backend.zip
    dest: /tmp

- name: Unzip backend
  become: true
  unarchive:
    src: /tmp/backend.zip
    dest: /home/ubuntu
    remote_src: yes

- name: Start Sever
  raw: |
    bash -c "cd backend >> /tmp/debug.log"
    sudo npm install
    sudo npm run build
    npm start:prod