---
# - name: Creates directory
#   file:
#     path: ~/web
#     state: directory

# - name: Copy index test page
#   template:
#     src: "backend/dist/*"
#     dest: "~/web"

- name: CD backend
  shell: |
    cd ./backend

- name: Executing node
  shell: |
    pm2 start 