---

- name: Copy backend to temp
  become: true
  copy:
    src: /root/project/backend.tar.gz
    dest: /tmp

- name: Unzip backend
  become: true
  unarchive:
    src: /tmp/backend.tar.gz
    dest: /home/ubuntu
    remote_src: yes

- name: Start Sever
  raw: |
    cd backend
    sudo npm install -g npm@latest
    sudo npm install
    sudo npm audit fix
    sudo npm run build
    npm start:prod